# Generated by Django 4.0.3 on 2022-04-22 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=256)),
                ('critere', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pathologies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('categorie', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Symptomes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=256)),
                ('exercices', models.ManyToManyField(to='PathologieApp.exercices')),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('sexe', models.CharField(max_length=100)),
                ('datePermis', models.CharField(max_length=100)),
                ('autreMaladies', models.CharField(max_length=100)),
                ('pathologie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PathologieApp.pathologies')),
            ],
        ),
        migrations.AddField(
            model_name='pathologies',
            name='symptomes',
            field=models.ManyToManyField(to='PathologieApp.symptomes'),
        ),
    ]
